-- Add ai_description field to assets table
-- This field will store an overall description of the image generated by AI

-- Add the ai_description column if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
      AND table_name = 'assets' 
      AND column_name = 'ai_description'
  ) THEN
    ALTER TABLE assets ADD COLUMN ai_description text;
  END IF;
END $$;

-- Add an index for efficient queries on ai_description
CREATE INDEX IF NOT EXISTS idx_assets_ai_description ON assets(ai_description) WHERE ai_description IS NOT NULL;
