# Railway configuration for production (backup)
[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y poppler-utils graphicsmagick imagemagick && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
