# Railway configuration for debugging production issues
# This version keeps production build but enables debug logging
[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
NUXT_DEBUG = "true"
